### PR TITLE
Update admin places in/around Jammu and Kashmir

### PR DESCRIPTION
**Pull request by stepps00**
Will fix: https://github.com/whosonfirst-data/whosonfirst-data/issues/1690
Should be merged alongside: https://github.com/whosonfirst-data/whosonfirst-data-admin-xx/pull/22

This PR:
- [x] Adjusts region geometries to align with existing country boundaries
- [x] Adjusts county geometries to align with existing country boundaries
- [x] Supersedes the existing Jammu and Kashmir region record into two new region records (Jammu and Kashmir, and Ladakh)
- [x] Supersedes the county record for the Saichen Glacier into a new record in the xx repo
- [x] Updates alt files, properties, concordances, and names as needed
- [x] Includes PIP work to update hierarchies and parent ids
- [x] Validates all geojson, geometry, and property changes

### CODE REVIEW

**Comment by stepps00** [comment]
_existing county geometries (blue), over country boundaries (red)_
Screen Shot 2022-12-08 at 8 54 02 AM

_new county geometries (pink), over country boundaries (red)_
Screen Shot 2022-12-08 at 8 54 21 AM

_existing region geometries (brown), over country boundaries (red)_
Screen Shot 2022-12-08 at 8 52 54 AM

_new region geometries (orange), over country boundaries (red)_
Screen Shot 2022-12-08 at 8 53 44 AM

_existing and new Jammu and Kashmir disputed geometries, showing the difference in the southern boundary_
Screen Shot 2022-12-08 at 8 54 55 AM

**Review by nvkelso — APPROVED** [review]
We reviewed heads-up in QGIS and I've spot checked the diff here.

**Comment by stepps00** [comment]
PIP work has started on this issue, I'll QA and comment again once a new commit is in.

**Comment by stepps00** [comment]
The most recent commit in this PR includes the PIP work for all updated features and descendants. All changes validate.

**Comment by stepps00** [comment]
I pulled down these records and QAd the changes, everything looks as expected, so I'm merging shortly.

**Pull request merged**
