### PR TITLE
Update Pune area admin records

### PR DESCRIPTION
**Pull request by stepps00**
This PR will fix a portion of https://github.com/whosonfirst-data/whosonfirst-data/issues/1593, specifically around Pune. See commit notes below.

To do:
- [x] Update locality records (polygons)
- [x] Update locality records (points)
- [x] Update borough records
- [x] Update neighbourhood records
- [x] Ensure alt files have all necessary properties
- [x] QA all leftover neighbourhood points, adjust names and geometries, superseding as necessary
- [x] Validate
- [ ] PIP

### CODE REVIEW

**Comment by stepps00** [comment]
f8a1957: Updates the geometries of Pune and Pimpri-Chinchwad localities, but does not store the existing geometries as alt files, as the geometries are already whosonfirst-sourced. Also flags one nearby locality record as funky.

8a9ed8a: This commit does two things, it: 
  - Adds new borough records to Pune
  - Moves any locality points that fall within the new Pune and Pimpri-Chinchwad to the neighbourhood placetype (but only if they're _not_ `mz:is_funky` of 1)

**Comment by stepps00** [comment]
Pune updates are relatively straightforward, since we're adding new boroughs and updating a minimal amount of neighbourhoods. Once approved, I'll PIP and validate this branch.

**Comment by nvkelso** [comment]
I recommended a few minor adjustments IRL, will review on new comment.

**Comment by stepps00** [comment]
The neighbourhood placetype was cleaned up in three recent commits. This is ready for QA/validation/PIP work.

**Comment by stepps00** [comment]
I've added commits to validate and PIP all records in this branch. I'll QA once more, then merge.

**Comment by stepps00** [comment]
For what it's worth, new borough shapes:
Screen Shot 2019-12-02 at 4 34 31 PM

And new locality polygons with neighbourhood point coverage:
Screen Shot 2019-12-02 at 4 36 51 PM

**Comment by stepps00** [comment]
Looks good, merging.

**Pull request merged**
