### PR TITLE
Update Place Sadarval

### PR DESCRIPTION
**Pull request by stepps00**
Updating `data/124/276/696/1/1242766961.geojson` using the [WOF Editor](https://github.com/iandees/wof-editor)

### CODE REVIEW

**Review by nvkelso — COMMENTED** [review]
I'm not sure about this one. I can't confirm it myself.

Can you comment your research material, please?

**Comment by stepps00** [comment]
There are limited resources for some of the smaller villages in India.. but I was able to confirm this on place name on both HERE and Bing Maps, along with a local Indian news site:

- https://www.indiatvnews.com/pincode/gujarat/navsari/fadvel
- https://www.bing.com/maps (lat,lng around 20.742511, 73.180607)
- https://mobile.here.com/ (lat,lng around 20.742511, 73.180607. Must be zoomed to ~admin2 level for label to appear)

I seem to be unable to link to HERE or Bing using the lat/lng in the URL...

**Comment by nvkelso** [comment]
I think these are two different places. If we're missing the Fadvel, let's add it as a new place. Either close the PR.

**Comment by stepps00** [comment]
Closing this PR, this place record is OK as-is.

**Pull request closed without merging**
